import Link from 'next/link';
import StaticInfoPage from '../components/StaticInfoPage';

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://zenithfcm.com';

export const metadata = {
  title: 'Disclaimer | ZenithFCM - Platform Notice & Data Accuracy',
  description: 'Read the ZenithFCM Disclaimer. Understand our relationship with EA Sports, data accuracy policies, and terms of use for our FC Mobile tools and database.',
  alternates: { canonical: '/disclaimer' },
  openGraph: {
    title: 'Disclaimer | ZenithFCM',
    description: 'Official disclaimer regarding ZenithFCM content, affiliations, and data accuracy for FC Mobile users.',
    url: `${siteUrl}/disclaimer`,
    siteName: 'ZenithFCM',
    type: 'website'
  }
};

export default function DisclaimerPage() {
  return (
    <StaticInfoPage
      title="Disclaimer"
      intro="Last Updated: May 5, 2026. ZenithFCM is an independent, fan-operated informational platform built for the FC Mobile (EA FC) community. Please read this disclaimer carefully before using our services."
      sections={[
        {
          heading: '1. Non-Affiliation Notice',
          body: (
            <p>
              ZenithFCM is <strong>not</strong> affiliated with, endorsed by, sponsored by, or officially connected to Electronic Arts Inc. (EA), EA Sports, or any of its subsidiaries. All game titles, trademarks, logos, and brand names (including "FC Mobile", "FIFA", and "EA Sports") are the property of their respective owners.
            </p>
          )
        },
        {
          heading: '2. Data Accuracy & Reliability',
          body: (
            <>
              <p>
                The information provided on ZenithFCM—including player statistics, market prices, and game database entries—is for informational purposes only. While we strive for precision:
              </p>
              <ul>
                <li><strong>Dynamic Updates:</strong> In-game data can change without notice due to updates, patches, or live events.</li>
                <li><strong>Market Fluctuations:</strong> Market values are estimations based on tracked trends and may not reflect real-time in-game availability.</li>
                <li><strong>No Guarantees:</strong> We provide no warranty regarding the completeness or absolute accuracy of the data.</li>
              </ul>
            </>
          )
        },
        {
          heading: '3. Tools & Calculators',
          body: (
            <p>
              Our tools (e.g., Squad Builder, Training Simulators) are designed to assist players in planning and strategy. Results generated by these tools are simulations and may differ from actual in-game outcomes due to hidden mechanics or specific game variables.
            </p>
          )
        },
        {
          heading: '4. External Links & Content',
          body: (
            <p>
              ZenithFCM may contain links to third-party websites or services. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party sites. Accessing external links is done at your own risk.
            </p>
          )
        },
        {
          heading: '5. Limitation of Liability',
          body: (
            <p>
              In no event shall ZenithFCM or its contributors be liable for any losses or damages (including, but not limited to, loss of in-game currency, account issues, or data loss) arising from the use of our platform or reliance on the information provided herein.
            </p>
          )
        },
        {
          heading: '6. User Responsibility',
          body: (
            <p>
              Users are responsible for ensuring that their use of ZenithFCM and its tools complies with the official Terms of Service of the games they play.
            </p>
          )
        },
        {
          heading: '7. Updates to This Disclaimer',
          body: (
            <>
              <p>
                We reserve the right to modify this disclaimer at any time. Changes will be posted on this page with an updated "Last Updated" date.
              </p>
              <p>
                For further information, please review our <Link href="/terms-and-conditions" style={{ color: '#2dd5c0' }}>Terms and Conditions</Link> and <Link href="/privacy-policy" style={{ color: '#2dd5c0' }}>Privacy Policy</Link>.
              </p>
            </>
          )
        }
      ]}
    />
  );
}
